// W079 — the PRODUCTION certification browser fixture.
//
// One REAL browser page per test against the hosted production URL, with
// the W076 discipline carried over verbatim and the W079 contract's
// evidence law enforced structurally:
//
//   * console/pageerror/requestfailed/HTTP violation collectors attached
//     from the very first navigation (the W076 helpers — same filter,
//     same documented noise classes);
//   * a journey TRANSCRIPT recorder (every named step + URL);
//   * full-page screenshots at decisive checkpoints, written under the
//     RUN's evidence directory (docs/productization-evidence/W079/
//     production-run-<a|b>/) — the driver wipes the run directory before
//     every pass, so recycled evidence is structurally impossible;
//   * the per-test record (results/<testId>.json) carrying the journey
//     id, the browser context, the FINAL Playwright status and the
//     evidence inventory — the global teardown folds these records into
//     the machine-readable browser-run digest the certification driver
//     reads (contract §9: the evidence is generated by the same
//     execution that produced the verdict);
//   * the zero-violation assertion, enforced in-test AND at fixture
//     teardown so no journey can end dirty.
//
// Authentication is ALWAYS the real production flow (helpers.ts): fresh
// sign-up through /signup, sign-in through /signin, sign-out through the
// real button. No quick-access panel exists in production (it is
// fail-closed there by design), no API/token bypass is used anywhere,
// and no seeded demo tenant exists to lean on.

import { expect, test as baseTest } from '@playwright/test';
import type { Page } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { attachViolationCollectors } from '../helpers/errors';
import type { Violation } from '../helpers/errors';

/** The production target (set by the certification driver). */
export const BASE_URL = process.env.W079_BASE_URL ?? '';
/** This run's evidence directory (absolute — inside the repo). */
export const RUN_DIR = process.env.W079_RUN_DIR ?? '';
/** The run label ('A' or 'B'). */
export const RUN_LABEL = process.env.W079_RUN_LABEL ?? '?';
/** The secrets scratch directory (wiped by the driver after the run). */
export const SECRETS_DIR = process.env.W079_SECRETS_DIR ?? '';

if (BASE_URL === '' || RUN_DIR === '' || SECRETS_DIR === '') {
  throw new Error(
    'the production certification suite requires W079_BASE_URL, W079_RUN_DIR and W079_SECRETS_DIR (run it through the certification driver — bun run cert:production)',
  );
}

/** Where the per-test records land (the digest's source of truth). */
export const RESULTS_DIR = path.join(RUN_DIR, 'results');
/** Full-page screenshots land here (one PNG per decisive moment). */
export const SCREEN_DIR = path.join(RUN_DIR, 'screenshots');
/** Journey transcripts land here (one JSON per test). */
export const TRANSCRIPT_DIR = path.join(RUN_DIR, 'transcripts');
/** Error captures land here (one JSON per test — the zero-violation record). */
export const ERROR_DIR = path.join(RUN_DIR, 'errors');

/** One recorded journey step. */
export interface TranscriptEntry {
  at: string;
  step: string;
  url: string;
  /** The screenshot this step captured (repo-relative path). */
  shot: string | null;
}

/** The production journey object the specs drive. */
export interface CertJourney {
  /** The real browser page of this test. */
  page: Page;
  /** Every violation captured so far (the zero-error contract's subject). */
  violations: Violation[];
  /** The journey transcript recorded so far. */
  transcript: TranscriptEntry[];
  /** Record a named step in the transcript. */
  step: (name: string) => Promise<void>;
  /** Capture a full-page screenshot (the decisive moments) + record it. */
  shot: (name: string) => Promise<void>;
  /** Assert ZERO console/network violations for the journey so far. */
  expectZeroViolations: () => void;
}

/** The per-test record (folded into the digest by the global teardown). */
export interface TestRecord {
  testId: string;
  journeyId: string;
  context: 'desktop' | 'mobile';
  status: 'pass' | 'fail' | 'flaky' | 'skipped';
  title: string;
  file: string;
  durationMs: number;
  error: string | null;
  violations: number;
  evidence: {
    transcripts: string[];
    screenshots: string[];
    errorCaptures: string[];
    results: string[];
  };
}

/** Extract the J-id every certification test title must begin with. */
export function journeyIdOfTitle(title: string): string {
  const match = /^J(\d{2})\b/.exec(title);
  if (match === null) {
    throw new Error(
      `the certification test "${title}" must be titled "JNN — …" (the J-id drives the digest)`,
    );
  }
  return `J${match[1]}`;
}

/** Turn a title into a stable slug (bounded length). */
function titleSlug(title: string): string {
  return title
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)
    .toLowerCase();
}

/** A short journey slug from the J-id + title (used in file names). */
function journeySlug(journeyId: string, title: string): string {
  const tail = titleSlug(title).replace(/^j\d{2}-/, '');
  return `${journeyId.toLowerCase()}-${tail === '' ? 'journey' : tail.slice(0, 34)}`;
}

/** Repo-relative path of an absolute evidence file. */
function repoRelative(file: string): string {
  return path.relative(process.cwd(), file).split(path.sep).join('/');
}

/** Write one JSON artifact, creating the directory as needed (returns the repo-relative path). */
async function writeJson(dir: string, name: string, body: unknown): Promise<string> {
  await mkdir(dir, { recursive: true });
  const file = path.join(dir, `${name}.json`);
  await writeFile(file, `${JSON.stringify(body, null, 2)}\n`, 'utf8');
  return repoRelative(file);
}

/**
 * The W079 certification test. Use in place of the bare `test`:
 *
 *   import { certTest as test } from './fixtures';
 *
 * Every test title MUST begin with its journey id ("J02 — …"); the file
 * name must end in -desktop.spec.ts or -mobile.spec.ts so the Playwright
 * projects pick it up and the digest's context is honest.
 */
export const certTest = baseTest.extend<{ cert: CertJourney }>({
  cert: async ({ page }, use, testInfo) => {
    const violations: Violation[] = [];
    attachViolationCollectors(page, violations);
    const transcript: TranscriptEntry[] = [];
    const journeyId = journeyIdOfTitle(testInfo.title);
    const context: 'desktop' | 'mobile' = testInfo.project.name === 'mobile' ? 'mobile' : 'desktop';
    const slug = `${journeySlug(journeyId, testInfo.title)}-${context}`;
    const testId = `${slug}:${context}`;
    const screenshots: string[] = [];

    const cert: CertJourney = {
      page,
      violations,
      transcript,
      step: async (name: string) => {
        transcript.push({
          at: new Date().toISOString(),
          step: name,
          url: page.url(),
          shot: null,
        });
      },
      shot: async (name: string) => {
        const file = path.join(SCREEN_DIR, `${slug}__${titleSlug(name)}.png`);
        await page.screenshot({ path: file, fullPage: true });
        const relative = repoRelative(file);
        screenshots.push(relative);
        transcript.push({
          at: new Date().toISOString(),
          step: `screenshot: ${name}`,
          url: page.url(),
          shot: relative,
        });
      },
      expectZeroViolations: () => {
        expect(
          violations,
          'the production journey produced browser errors (console/pageerror/requestfailed/http)',
        ).toEqual([]);
      },
    };

    await use(cert);

    // Finalize: the evidence artifacts are written for EVERY outcome
    // (pass or fail), and the zero-violation contract is enforced once
    // more so no journey can end dirty after its last assertion.
    const transcriptPath = await writeJson(TRANSCRIPT_DIR, slug, {
      spec: testInfo.file,
      title: testInfo.title,
      project: testInfo.project.name,
      runLabel: RUN_LABEL,
      steps: transcript,
    });
    const errorPath = await writeJson(ERROR_DIR, slug, {
      spec: testInfo.file,
      title: testInfo.title,
      project: testInfo.project.name,
      runLabel: RUN_LABEL,
      violationCount: violations.length,
      violations,
      documentedFilter: [
        'favicon 404s (/favicon.ico — no favicon asset ships; browser-automatic request noise)',
        'net::ERR_ABORTED request cancellations (navigation/close mid-request bookkeeping)',
        'Chromium password-manager caret-color hydration warnings (browser-injected style attribute; every other hydration mismatch fails)',
      ],
    });

    const status: TestRecord['status'] =
      testInfo.status === 'passed' ? 'pass' : testInfo.status === 'skipped' ? 'skipped' : 'fail';

    const record: TestRecord = {
      testId,
      journeyId,
      context,
      status,
      title: testInfo.title,
      file: repoRelative(testInfo.file),
      durationMs: testInfo.duration,
      error:
        testInfo.error === undefined
          ? null
          : `${testInfo.error.message ?? String(testInfo.error)}`.slice(0, 800),
      violations: violations.length,
      evidence: {
        transcripts: [transcriptPath],
        screenshots,
        errorCaptures: [errorPath],
        results: [repoRelative(path.join(RESULTS_DIR, `${testId.replace(/:/g, '-')}.json`))],
      },
    };
    await writeJson(RESULTS_DIR, testId.replace(/:/g, '-'), record);

    expect(
      violations,
      `[teardown] the production journey ended with browser violations: ${JSON.stringify(violations)}`,
    ).toEqual([]);
  },
});

export { expect };
