// W079 — the certification browser suite's global teardown.
//
// Folds the per-test records the fixture wrote (RUN_DIR/results/*.json)
// into the machine-readable browser-run digest the certification driver
// reads (browser-run-digest.json): the Playwright totals, the per-test
// outcomes keyed by journey id + browser context, the zero-violation
// record, and the evidence inventory. This runs in the SAME Playwright
// execution that produced the results — the digest is generated by the
// same execution that produced the verdict (contract §9), never
// hand-assembled afterwards.
//
// Honesty rules (the driver's gate-three evaluator re-checks all of
// these against the contract):
//   * a journey-context pair with NO record is simply absent — the
//     evaluator reports it as a missing mandatory test (a FAIL, never a
//     silent skip);
//   * records are never filtered — a failing test lands in the digest
//     with its error text;
//   * the violations column is the fixture's own count of captured
//     console/pageerror/requestfailed/HTTP>=400 events.

import { readFile, writeFile } from 'node:fs/promises';
import { readdir } from 'node:fs/promises';
import path from 'node:path';
import type { TestRecord } from './fixtures';

/** The digest the driver's gate-three evaluator consumes. */
interface BrowserRunDigest {
  total: number;
  passed: number;
  failed: number;
  flaky: number;
  skipped: number;
  tests: {
    testId: string;
    journeyId: string;
    context: 'desktop' | 'mobile';
    status: 'pass' | 'fail' | 'flaky' | 'skipped';
    title: string;
    file: string;
    durationMs: number;
    error: string | null;
    /** The honest BLOCKED channel (W101) — carried verbatim, never filtered. */
    blockedReasons?: string[];
    blockedEvidence?: Record<string, unknown>;
  }[];
  violations: { testId: string; violations: number }[];
  evidence: {
    transcripts: string[];
    screenshots: string[];
    errorCaptures: string[];
    results: string[];
  };
}

export default async function globalTeardown(): Promise<void> {
  const runDir = process.env.W079_RUN_DIR ?? '';
  if (runDir === '') {
    throw new Error('W079_RUN_DIR is not set — run the suite through the certification driver');
  }
  const resultsDir = path.join(runDir, 'results');
  const files = (await readdir(resultsDir).catch(() => []))
    .filter((name) => name.endsWith('.json'))
    .sort();

  const records: TestRecord[] = [];
  for (const name of files) {
    try {
      records.push(JSON.parse(await readFile(path.join(resultsDir, name), 'utf8')) as TestRecord);
    } catch {
      // A corrupt record is dropped from the digest — the affected test
      // then counts as MISSING (a fail at the evaluator), never as pass.
    }
  }

  const digest: BrowserRunDigest = {
    total: records.length,
    passed: records.filter((record) => record.status === 'pass').length,
    failed: records.filter((record) => record.status === 'fail').length,
    flaky: records.filter((record) => record.status === 'flaky').length,
    skipped: records.filter((record) => record.status === 'skipped').length,
    tests: records.map((record) => ({
      testId: record.testId,
      journeyId: record.journeyId,
      context: record.context,
      status: record.status,
      title: record.title,
      file: record.file,
      durationMs: record.durationMs,
      error: record.error,
      ...(record.blockedReasons !== undefined && record.blockedReasons.length > 0
        ? { blockedReasons: record.blockedReasons }
        : {}),
      ...(record.blockedEvidence !== undefined && Object.keys(record.blockedEvidence).length > 0
        ? { blockedEvidence: record.blockedEvidence }
        : {}),
    })),
    violations: records.map((record) => ({
      testId: record.testId,
      violations: record.violations,
    })),
    evidence: {
      transcripts: records.flatMap((record) => record.evidence.transcripts),
      screenshots: records.flatMap((record) => record.evidence.screenshots),
      errorCaptures: records.flatMap((record) => record.evidence.errorCaptures),
      results: records.flatMap((record) => record.evidence.results),
    },
  };

  await writeFile(
    path.join(runDir, 'browser-run-digest.json'),
    `${JSON.stringify(digest, null, 2)}\n`,
    'utf8',
  );
  process.stderr.write(
    `[w079] browser matrix digest: ${digest.passed}/${digest.total} passed · ` +
      `${digest.failed} failed · ${digest.flaky} flaky · ${digest.skipped} skipped\n`,
  );
}
