// W079 — the evidence emission (PURE: JSON + markdown renderers over the
// run results). The driver writes exactly what these produce — the
// committed evidence tree is machine-generated by the same execution
// that produced the verdict (contract §9). No secret value ever passes
// through this module: the run results carry verdicts, counters, paths
// and identities only.

import type {
  CertificationCheck,
  CertificationRunResult,
  FinalCertification,
  JourneyResult,
} from './types';
import { journeySpec } from './matrix';

function statusMark(status: string): string {
  if (status === 'pass' || status === 'CERTIFIED READY') return '✅';
  if (status === 'blocked' || status === 'BLOCKED') return '⛔';
  return '❌';
}

/** The machine-readable run result (docs/.../<run>/run-result.json). */
export function runResultToJson(run: CertificationRunResult): string {
  return `${JSON.stringify(run, null, 2)}\n`;
}

/** The deployment identity manifest (docs/.../<run>/deployment-identity.json). */
export function identityManifestToJson(run: CertificationRunResult): string {
  return `${JSON.stringify(run.identity, null, 2)}\n`;
}

/** The command/config manifest (docs/.../<run>/command-manifest.json). */
export function commandManifestToJson(run: CertificationRunResult): string {
  return `${JSON.stringify(
    {
      run: run.runLabel,
      target: run.target,
      command: run.command,
      evidenceDir: run.evidenceDir,
      repoGates: run.repoGates.map((gate) => ({ command: gate.command, exitCode: gate.exitCode })),
      browserRunner: 'node node_modules/@playwright/test/cli.js test -c playwright.certification.config.ts',
      notes: [
        'Evidence generated by the same execution that produced the verdict (contract §9).',
        'No secret value (worker token, API key, provider credential) is recorded in this tree.',
        'The browser matrix authenticates through the real production sign-up/sign-in flow only.',
      ],
    },
    null,
    2,
  )}\n`;
}

/** The gates section of the run report. */
function gatesTable(gates: CertificationCheck[]): string {
  if (gates.length === 0) return '_No gate checks recorded._';
  return [
    '| Verdict | Gate | Observation |',
    '| --- | --- | --- |',
    ...gates.map(
      (gate) =>
        `| ${statusMark(gate.status)} \`${gate.status.toUpperCase()}\` | \`${gate.id}\` | ${escapeCell(
          gate.detail,
        )} |`,
    ),
  ].join('\n');
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').slice(0, 500);
}

/** The journey table of the run report. */
function journeysTable(journeys: JourneyResult[]): string {
  return [
    '| Verdict | Journey | Mandatory proof | Contexts |',
    '| --- | --- | --- | --- |',
    ...journeys.map((journey) => {
      const spec = journeySpec(journey.journeyId);
      const contexts = journey.contexts
        .map((entry) => `${entry.context}:${entry.status}`)
        .join(' · ');
      return `| ${statusMark(journey.status)} \`${journey.status.toUpperCase()}\` | **${journey.journeyId}** ${escapeCell(
        spec.title,
      )} | ${escapeCell(spec.mandatoryProof)} | ${escapeCell(contexts)} |`;
    }),
  ].join('\n');
}

/** The run report (docs/.../<run>/run-report.md). */
export function runReportToMarkdown(run: CertificationRunResult): string {
  const w078 =
    run.w078 === null
      ? '_No W078 hosted smoke rerun embedded._'
      : `\`${run.w078.label}\` — ${run.w078.summary.passed} passed · ${run.w078.summary.failed} failed · ${run.w078.summary.blocked} blocked · ${run.w078.summary.skipped} skipped (report: ${
          run.w078.reportPath ?? 'not written'
        })`;
  return `# W079 production journey certification — Run ${run.runLabel}

- **Target:** ${run.target}
- **Deployment:** \`${run.identity.deploymentId}\` @ \`${run.identity.commitSha}\` (created ${run.identity.deploymentCreatedAt})
- **Run:** ${run.startedAt} → ${run.finishedAt}
- **Command:** \`${run.command}\`
- **Evidence:** \`${run.evidenceDir}\`

## Infrastructure gates (G1/G3)

${gatesTable(run.gates)}

## Repository gates (G2)

${run.repoGates
  .map((gate) => `- \`${gate.command}\` → exit ${gate.exitCode === null ? 'unknown' : gate.exitCode} — ${escapeCell(gate.summary)}`)
  .join('\n')}

## W078 hosted smoke rerun (operations proof, contract §8)

${w078}

## Journey matrix (J01–J15)

${journeysTable(run.journeys)}

## Summary

**${run.summary.passed} passed · ${run.summary.failed} failed · ${run.summary.blocked} blocked · ${run.summary.flaky} flaky · ${run.summary.unexpected} unexpected**

Run verdict: **${run.verdict}**
`;
}

/** The final verdict file (docs/.../final-verdict.json). */
export function finalVerdictToJson(final: FinalCertification): string {
  return `${JSON.stringify(
    {
      verdict: final.verdict,
      generatedAt: final.generatedAt,
      reasons: final.reasons,
      checks: final.checks,
      runA: final.runA === null ? null : { dir: final.runA.evidenceDir, summary: final.runA.summary },
      runB: final.runB === null ? null : { dir: final.runB.evidenceDir, summary: final.runB.summary },
    },
    null,
    2,
  )}\n`;
}

/**
 * The canonical certification document
 * (docs/productization-evidence/W079/W079-PRODUCTION-JOURNEY-CERTIFICATION.md)
 * — contract §9's required root file.
 */
export function finalCertificationToMarkdown(final: FinalCertification): string {
  const runSection = (run: CertificationRunResult | null): string => {
    if (run === null) return '_missing_';
    return [
      `- **Run ${run.runLabel}:** ${run.startedAt} → ${run.finishedAt} (${run.evidenceDir})`,
      `  - deployment \`${run.identity.deploymentId}\` @ \`${run.identity.commitSha}\` (${run.identity.environmentLabel}/${run.identity.databaseBackendClass})`,
      `  - **${run.summary.passed} passed · ${run.summary.failed} failed · ${run.summary.blocked} blocked · ${run.summary.flaky} flaky · ${run.summary.unexpected} unexpected** → ${run.verdict}`,
    ].join('\n');
  };
  const reasons =
    final.reasons.length === 0
      ? '_none — every mandatory gate passed on both runs against the same deployment revision._'
      : final.reasons.map((reason) => `- ${escapeCell(reason)}`).join('\n');
  return `# W079 — Production Journey Certification & Release Gate

**Generated:** ${final.generatedAt}
**Verdict:** ${statusMark(final.verdict)} **${final.verdict}**

The canonical contract is \`spec/PRODUCTION-JOURNEY-CERTIFICATION-2026-09-23.md\`; the verdict vocabulary is its §2/§11 exactly. Evidence is machine-generated by the same execution that produced the verdict (§9); no secret value is recorded anywhere in this tree.

## The two-run rule (contract §7)

${runSection(final.runA)}

${runSection(final.runB)}

## Finalizer checks

${gatesTable(final.checks)}

## Why this verdict

${reasons}

## Operations proof carried in (contract §8)

The W078 operations records this certification links (not restates):

- duplicate/idempotent execution — the production smoke rerun's \`worker.duplicate-acknowledged\`;
- deterministic dead-letter/not-found handling — \`worker.dead-letter-invalid\` / \`worker.not-found-consumed\`;
- retry policy/attempt limits — \`worker.retry-policy-surface\`;
- health/readiness — \`health.contract\` / \`health.green\`;
- worker observability — \`observability.worker-snapshot\` / \`observability.metrics-advance\` / \`observability.surfaces-agree\`;
- queue counters, migration/redeploy determinism, rollback target/runbook, environment separation — the W078 committed evidence tree at \`docs/productization-evidence/W078/\` (production-dogfood, deployment-artifact-preview, deployment-artifact-preview-rerun) and the embedded production rerun reports under each run's \`w078/\` sub-directory.

## Reproducing the certification

\`\`\`bash
# one certification pass (Run A, then Run B — same deployment revision)
bun run cert:production -- --target https://aurum-chat-livid.vercel.app \\
  --run a --deployment-id <dpl> --expect-commit <sha> --deployment-created <iso> \\
  --worker-token-file <path> --vercel-token-file <path>
# the finalizer (verdict + this document)
bun run cert:production -- --finalize
\`\`\`

The browser matrix authenticates through the real production sign-up flow only — no quick-login, no API/token bypass, no seeded demo tenant (G3).
`;
}
