// W079/W101 — the production journey certification operator CLI.
//
//   # one certification pass (Run A, then Run B — the SAME deployment revision)
//   bun run cert:production -- --target https://aurum-chat-livid.vercel.app \
//        --run a --deployment-id dpl_X --expect-commit <sha> --deployment-created <iso> \
//        --worker-token-file <path> --vercel-token-file <path>
//
//   # the post-S002 program (W101 — the full J01–J22 matrix, the W101
//   # evidence root docs/productization-evidence/W101, the rollback gate)
//   bun run cert:production -- --program w101 --target … --run a …
//
//   # the finalizer (the two-run verdict + the canonical document)
//   bun run cert:production -- --finalize [--program w101]
//
// Each pass (contract §5-§9): the G1 read-only infrastructure probes, the
// G2 repository gates, the G3 W078 hosted smoke rerun (embedded as the
// §8 operations proof) and the J01–J15 browser matrix over real Chromium
// against the hosted production URL (desktop 1280×800 + mobile touch
// 390×844, real production authentication, screenshots/transcripts/error
// captures). The evidence tree lands under
// docs/productization-evidence/W079/production-run-<a|b>/ — machine-
// generated by the same execution that produced the verdict.
//
// The finalizer enforces the two-run same-revision rule (contract §7):
// CERTIFIED READY only when BOTH runs are 0 failed · 0 blocked · 0 flaky ·
// 0 unexpected AND the runs agree on the journey matrix and the
// deployment identity. Anything less stays BLOCKED (or FAILED) — never
// laundered.
//
// SECRETS: the worker seam token and the Vercel API token arrive as FILE
// PATHS, are read once by the driver, live in memory only, and never
// enter any artifact. Exit codes:
//   0 — the pass (or the finalization) is green
//   1 — a real failure (FAIL verdict, or the run could not execute)
//   2 — BLOCKED (a documented external precondition is missing)

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  finalCertificationToMarkdown,
  finalVerdict,
  finalVerdictToJson,
  runCertificationPass,
} from '../src/modules/release-certification/contract';
import type {
  CertificationProgram,
  CertificationRunResult,
} from '../src/modules/release-certification/contract';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..');

/**
 * The program model (W101): 'w079' is the frozen historical program
 * (J01–J15, the W079 evidence root, the W079 document names); 'w101' is
 * the post-S002 program (the full J01–J22 matrix, the W101 evidence
 * root, the W101 repository identity and the rollback-evidence gate).
 */
const PROGRAMS: Record<
  CertificationProgram,
  {
    evidenceRoot: string;
    documentName: string;
    repository: { branch: string; baseCommit: string };
  }
> = {
  W079: {
    evidenceRoot: path.join('docs', 'productization-evidence', 'W079'),
    documentName: 'W079-PRODUCTION-JOURNEY-CERTIFICATION.md',
    repository: {
      branch: 'work/w079-production-certification',
      baseCommit: 'c0ea5f78f8979d46029ac6124eff2bf0ebd6d988',
    },
  },
  W101: {
    evidenceRoot: path.join('docs', 'productization-evidence', 'W101'),
    documentName: 'W101-PRODUCTION-JOURNEY-CERTIFICATION.md',
    repository: {
      branch: 'work/w101-final-certification',
      baseCommit: 'a2db98a25b5ff9756fa849d3e196a80bafba1104',
    },
  },
};

interface CliArgs {
  target: string | null;
  run: 'a' | 'b' | null;
  finalize: boolean;
  program: CertificationProgram;
  deploymentId: string | null;
  expectCommit: string | null;
  deploymentCreated: string | null;
  workerTokenFile: string | null;
  vercelTokenFile: string | null;
  skipRepoGates: boolean;
  repoGatesFrom: string | null;
}

function parseArgs(argv: readonly string[]): CliArgs {
  const args: CliArgs = {
    target: null,
    run: null,
    finalize: false,
    program: 'W079',
    deploymentId: null,
    expectCommit: null,
    deploymentCreated: null,
    workerTokenFile: null,
    vercelTokenFile: null,
    skipRepoGates: false,
    repoGatesFrom: null,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]!;
    const next = (): string => {
      const value = argv[i + 1];
      if (value === undefined || value.startsWith('--')) {
        console.error(`missing value for ${arg}`);
        process.exit(1);
      }
      i += 1;
      return value;
    };
    if (arg === '--target') args.target = next();
    else if (arg === '--run') {
      const value = next().toLowerCase();
      if (value !== 'a' && value !== 'b') {
        console.error(`--run must be a|b (got '${value}')`);
        process.exit(1);
      }
      args.run = value;
    } else if (arg === '--program') {
      const value = next().toLowerCase();
      if (value !== 'w079' && value !== 'w101') {
        console.error(`--program must be w079|w101 (got '${value}')`);
        process.exit(1);
      }
      args.program = value === 'w101' ? 'W101' : 'W079';
    } else if (arg === '--finalize') args.finalize = true;
    else if (arg === '--deployment-id') args.deploymentId = next();
    else if (arg === '--expect-commit') args.expectCommit = next();
    else if (arg === '--deployment-created') args.deploymentCreated = next();
    else if (arg === '--worker-token-file') args.workerTokenFile = next();
    else if (arg === '--vercel-token-file') args.vercelTokenFile = next();
    else if (arg === '--skip-repo-gates') args.skipRepoGates = true;
    else if (arg === '--repo-gates-from') args.repoGatesFrom = next();
    else if (arg === '--help' || arg === '-h') {
      console.log(
        [
          'usage: bun run cert:production -- --target <url> --run a|b',
          '         [--program w079|w101] --deployment-id <dpl> --expect-commit <sha> --deployment-created <iso>',
          '         [--worker-token-file <path>] [--vercel-token-file <path>]',
          '         [--repo-gates-from <dir>] [--skip-repo-gates]',
          '       bun run cert:production -- --finalize [--program w079|w101]',
          '',
          'programs: w079 (default) — the frozen J01–J15 matrix, the W079 evidence root;',
          '          w101       — the post-S002 J01–J22 matrix, the W101 evidence root,',
          '                       the rollback-evidence gate and the W101 repository identity.',
        ].join('\n'),
      );
      process.exit(0);
    } else {
      console.error(`unknown argument '${arg}'`);
      process.exit(1);
    }
  }
  return args;
}

/** Load one recorded run from the evidence tree (the finalizer's input). */
async function loadRun(
  label: 'a' | 'b',
  evidenceRoot: string,
): Promise<CertificationRunResult | null> {
  const file = path.join(REPO_ROOT, evidenceRoot, `production-run-${label}`, 'run-result.json');
  try {
    return JSON.parse(await readFile(file, 'utf8')) as CertificationRunResult;
  } catch {
    return null;
  }
}

async function main(): Promise<number> {
  const args = parseArgs(process.argv.slice(2));
  const program = args.program;
  const { evidenceRoot, documentName, repository } = PROGRAMS[program];

  // ---- the finalizer: the two-run same-revision verdict -------------------
  if (args.finalize) {
    const runA = await loadRun('a', evidenceRoot);
    const runB = await loadRun('b', evidenceRoot);
    const outcome = finalVerdict(runA, runB);
    const final = {
      verdict: outcome.verdict,
      runA,
      runB,
      reasons: outcome.reasons,
      checks: outcome.checks,
      generatedAt: new Date().toISOString(),
    };
    const outDir = path.join(REPO_ROOT, evidenceRoot);
    await writeFile(
      path.join(outDir, 'final-verdict.json'),
      finalVerdictToJson(final),
      'utf8',
    );
    await writeFile(
      path.join(outDir, documentName),
      finalCertificationToMarkdown(final),
      'utf8',
    );
    console.log(`\n=== ${program} FINAL VERDICT: ${final.verdict} ===`);
    for (const reason of final.reasons) console.log(`  - ${reason}`);
    console.log(`  evidence: ${evidenceRoot}/final-verdict.json`);
    if (final.verdict === 'CERTIFIED READY') return 0;
    return final.verdict === 'FAILED' ? 1 : 2;
  }

  // ---- one certification pass ---------------------------------------------
  if (args.run === null) {
    console.error('no run: pass --run a (or --run b); the finalizer is --finalize');
    return 1;
  }
  if (args.target === null || args.deploymentId === null || args.expectCommit === null) {
    console.error(
      'a certification pass requires --target, --deployment-id and --expect-commit ' +
        '(the deployment identity the run must verify — contract §3)',
    );
    return 1;
  }
  const command = `bun run cert:production -- --target ${args.target} --run ${args.run}` +
    (program === 'W101' ? ' --program w101' : '') +
    ` --deployment-id ${args.deploymentId} --expect-commit ${args.expectCommit}` +
    (args.deploymentCreated === null ? '' : ` --deployment-created ${args.deploymentCreated}`) +
    ' --worker-token-file <redacted> --vercel-token-file <redacted>';

  // Phase-split G2 evidence: pre-recorded gate results from real executions
  // against this tree (see the driver's repoGateResults contract note).
  let repoGateResults: Record<string, { command: string; exitCode: number | null; summary: string }> | undefined;
  if (args.repoGatesFrom !== null) {
    repoGateResults = {};
    for (const label of ['typecheck', 'tests', 'architecture', 'lint']) {
      const file = path.join(args.repoGatesFrom, `${label}.json`);
      try {
        repoGateResults[label] = JSON.parse(await readFile(file, 'utf8')) as {
          command: string;
          exitCode: number | null;
          summary: string;
        };
      } catch {
        console.error(`the repo-gate record '${file}' could not be read — record it first`);
        return 1;
      }
    }
  }

  const run = await runCertificationPass({
    target: args.target,
    program,
    runLabel: args.run === 'a' ? 'A' : 'B',
    expectedDeployment: {
      deploymentId: args.deploymentId,
      commitSha: args.expectCommit,
      createdAt: args.deploymentCreated ?? '',
    },
    workerTokenFile: args.workerTokenFile,
    vercelTokenFile: args.vercelTokenFile,
    repoRoot: REPO_ROOT,
    evidenceRoot,
    command,
    repository,
    skipRepoGates: args.skipRepoGates,
    repoGateResults,
  });

  console.log(`\n=== ${program} RUN ${run.runLabel} VERDICT: ${run.verdict} ===`);
  console.log(
    `  ${run.summary.passed} passed · ${run.summary.failed} failed · ${run.summary.blocked} blocked · ` +
      `${run.summary.flaky} flaky · ${run.summary.unexpected} unexpected`,
  );
  for (const gate of run.gates) {
    console.log(`  [${gate.status.toUpperCase()}] ${gate.id} — ${gate.detail.slice(0, 160)}`);
  }
  for (const journey of run.journeys) {
    if (journey.status !== 'pass') {
      console.log(`  [${journey.status.toUpperCase()}] ${journey.journeyId} — ${journey.detail.slice(0, 200)}`);
    }
  }
  console.log(`  evidence: ${run.evidenceDir}`);
  if (run.verdict === 'CERTIFIED READY') return 0;
  return run.verdict === 'FAILED' ? 1 : 2;
}

main().then(
  (code) => {
    process.exit(code);
  },
  (error) => {
    console.error('the certification pass could not run:', error);
    process.exit(1);
  },
);
