// W079 — the production journey certification operator CLI.
//
//   # one certification pass (Run A, then Run B — the SAME deployment revision)
//   bun run cert:production -- --target https://aurum-chat-livid.vercel.app \
//        --run a --deployment-id dpl_X --expect-commit <sha> --deployment-created <iso> \
//        --worker-token-file <path> --vercel-token-file <path>
//
//   # the finalizer (the two-run verdict + the canonical document)
//   bun run cert:production -- --finalize
//
// Each pass (contract §5-§9): the G1 read-only infrastructure probes, the
// G2 repository gates, the G3 W078 hosted smoke rerun (embedded as the
// §8 operations proof) and the J01–J15 browser matrix over real Chromium
// against the hosted production URL (desktop 1280×800 + mobile touch
// 390×844, real production authentication, screenshots/transcripts/error
// captures). The evidence tree lands under
// docs/productization-evidence/W079/production-run-<a|b>/ — machine-
// generated by the same execution that produced the verdict.
//
// The finalizer enforces the two-run same-revision rule (contract §7):
// CERTIFIED READY only when BOTH runs are 0 failed · 0 blocked · 0 flaky ·
// 0 unexpected AND the runs agree on the journey matrix and the
// deployment identity. Anything less stays BLOCKED (or FAILED) — never
// laundered.
//
// SECRETS: the worker seam token and the Vercel API token arrive as FILE
// PATHS, are read once by the driver, live in memory only, and never
// enter any artifact. Exit codes:
//   0 — the pass (or the finalization) is green
//   1 — a real failure (FAIL verdict, or the run could not execute)
//   2 — BLOCKED (a documented external precondition is missing)

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  finalCertificationToMarkdown,
  finalVerdict,
  finalVerdictToJson,
  runCertificationPass,
} from '../src/modules/release-certification/contract';
import type { CertificationRunResult } from '../src/modules/release-certification/contract';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..');
const EVIDENCE_ROOT = path.join('docs', 'productization-evidence', 'W079');

interface CliArgs {
  target: string | null;
  run: 'a' | 'b' | null;
  finalize: boolean;
  deploymentId: string | null;
  expectCommit: string | null;
  deploymentCreated: string | null;
  workerTokenFile: string | null;
  vercelTokenFile: string | null;
  skipRepoGates: boolean;
}

function parseArgs(argv: readonly string[]): CliArgs {
  const args: CliArgs = {
    target: null,
    run: null,
    finalize: false,
    deploymentId: null,
    expectCommit: null,
    deploymentCreated: null,
    workerTokenFile: null,
    vercelTokenFile: null,
    skipRepoGates: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]!;
    const next = (): string => {
      const value = argv[i + 1];
      if (value === undefined || value.startsWith('--')) {
        console.error(`missing value for ${arg}`);
        process.exit(1);
      }
      i += 1;
      return value;
    };
    if (arg === '--target') args.target = next();
    else if (arg === '--run') {
      const value = next().toLowerCase();
      if (value !== 'a' && value !== 'b') {
        console.error(`--run must be a|b (got '${value}')`);
        process.exit(1);
      }
      args.run = value;
    } else if (arg === '--finalize') args.finalize = true;
    else if (arg === '--deployment-id') args.deploymentId = next();
    else if (arg === '--expect-commit') args.expectCommit = next();
    else if (arg === '--deployment-created') args.deploymentCreated = next();
    else if (arg === '--worker-token-file') args.workerTokenFile = next();
    else if (arg === '--vercel-token-file') args.vercelTokenFile = next();
    else if (arg === '--skip-repo-gates') args.skipRepoGates = true;
    else if (arg === '--help' || arg === '-h') {
      console.log(
        [
          'usage: bun run cert:production -- --target <url> --run a|b',
          '         --deployment-id <dpl> --expect-commit <sha> --deployment-created <iso>',
          '         [--worker-token-file <path>] [--vercel-token-file <path>] [--skip-repo-gates]',
          '       bun run cert:production -- --finalize',
        ].join('\n'),
      );
      process.exit(0);
    } else {
      console.error(`unknown argument '${arg}'`);
      process.exit(1);
    }
  }
  return args;
}

/** Load one recorded run from the evidence tree (the finalizer's input). */
async function loadRun(label: 'a' | 'b'): Promise<CertificationRunResult | null> {
  const file = path.join(REPO_ROOT, EVIDENCE_ROOT, `production-run-${label}`, 'run-result.json');
  try {
    return JSON.parse(await readFile(file, 'utf8')) as CertificationRunResult;
  } catch {
    return null;
  }
}

async function main(): Promise<number> {
  const args = parseArgs(process.argv.slice(2));

  // ---- the finalizer: the two-run same-revision verdict -------------------
  if (args.finalize) {
    const runA = await loadRun('a');
    const runB = await loadRun('b');
    const outcome = finalVerdict(runA, runB);
    const final = {
      verdict: outcome.verdict,
      runA,
      runB,
      reasons: outcome.reasons,
      checks: outcome.checks,
      generatedAt: new Date().toISOString(),
    };
    const outDir = path.join(REPO_ROOT, EVIDENCE_ROOT);
    await writeFile(
      path.join(outDir, 'final-verdict.json'),
      finalVerdictToJson(final),
      'utf8',
    );
    await writeFile(
      path.join(outDir, 'W079-PRODUCTION-JOURNEY-CERTIFICATION.md'),
      finalCertificationToMarkdown(final),
      'utf8',
    );
    console.log(`\n=== W079 FINAL VERDICT: ${final.verdict} ===`);
    for (const reason of final.reasons) console.log(`  - ${reason}`);
    console.log(`  evidence: ${EVIDENCE_ROOT}/final-verdict.json`);
    if (final.verdict === 'CERTIFIED READY') return 0;
    return final.verdict === 'FAILED' ? 1 : 2;
  }

  // ---- one certification pass ---------------------------------------------
  if (args.run === null) {
    console.error('no run: pass --run a (or --run b); the finalizer is --finalize');
    return 1;
  }
  if (args.target === null || args.deploymentId === null || args.expectCommit === null) {
    console.error(
      'a certification pass requires --target, --deployment-id and --expect-commit ' +
        '(the deployment identity the run must verify — contract §3)',
    );
    return 1;
  }
  const command = `bun run cert:production -- --target ${args.target} --run ${args.run} ` +
    `--deployment-id ${args.deploymentId} --expect-commit ${args.expectCommit}` +
    (args.deploymentCreated === null ? '' : ` --deployment-created ${args.deploymentCreated}`) +
    ' --worker-token-file <redacted> --vercel-token-file <redacted>';

  const run = await runCertificationPass({
    target: args.target,
    runLabel: args.run === 'a' ? 'A' : 'B',
    expectedDeployment: {
      deploymentId: args.deploymentId,
      commitSha: args.expectCommit,
      createdAt: args.deploymentCreated ?? '',
    },
    workerTokenFile: args.workerTokenFile,
    vercelTokenFile: args.vercelTokenFile,
    repoRoot: REPO_ROOT,
    evidenceRoot: EVIDENCE_ROOT,
    command,
    skipRepoGates: args.skipRepoGates,
  });

  console.log(`\n=== W079 RUN ${run.runLabel} VERDICT: ${run.verdict} ===`);
  console.log(
    `  ${run.summary.passed} passed · ${run.summary.failed} failed · ${run.summary.blocked} blocked · ` +
      `${run.summary.flaky} flaky · ${run.summary.unexpected} unexpected`,
  );
  for (const gate of run.gates) {
    console.log(`  [${gate.status.toUpperCase()}] ${gate.id} — ${gate.detail.slice(0, 160)}`);
  }
  for (const journey of run.journeys) {
    if (journey.status !== 'pass') {
      console.log(`  [${journey.status.toUpperCase()}] ${journey.journeyId} — ${journey.detail.slice(0, 200)}`);
    }
  }
  console.log(`  evidence: ${run.evidenceDir}`);
  if (run.verdict === 'CERTIFIED READY') return 0;
  return run.verdict === 'FAILED' ? 1 : 2;
}

main().then(
  (code) => {
    process.exit(code);
  },
  (error) => {
    console.error('the certification pass could not run:', error);
    process.exit(1);
  },
);
